project:
  type: website

website:
  title: "Course documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - md-basics.qmd
      - programmer-dictionary.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



