---
title: "The Programmer Dictionary"
---

## A


### Algoexpert
: definition

---

### Arquitechture
: defintion

---

### Abstraction
: definition

---

### apt
: definition

---


### API Rest
: definition

---

### API Reference 
: definition

---

### Agile
: definition

---

### AWS
: definition

---

### Axios <span style="color:cornflowerblue;"><u>(React)</u></span>

---

## B

### Bash (.sh)
: definition

---

### Branch <span style="color:gray;">(<u>Git</u>)</span>
: definition

---

### Built-in
: definition

---


## C


### CI/CD
: definition

---

### Client
: defintion

---

### CLI (*Comand Line Interface*)
: defintion

---

### Class <span style="color:darkorange;">(<u>Java</u>)</span>

---

### Cloud
: definition

---

### Controller
: definition

---

### Component <span style="color:cornflowerblue;">(<u>React</u>)</span>
: defintion

---

### COP (*Component Oriented Programming*)
: definition

---

### curl (*Linux*)
: definition

---

### Cron Job
: definition

---

### CSS (Cascade Style Sheet)
: definition

---

## D


### Data Warehouse
: definition

---

### DB (Data Base)
: defintion

---

### DDD (Domain-Driven Design)
: definition

---

### (to) deploy
: definition

---

### Dependency
: definition

---

### Docker
: definition

---

### Domain (*Architecture*)
: definition

---


## E


### Eclipse
: definition

---

### ES6 (ECMAScript 2015)
: defintion

---

### Entity
: definition

---

### Express
: definition

---

## F

### Factory Design Pattern
: definition

---

### FATO
: definition

---

### Flameshot
: definition

---

### (*to*) fork
: definition

---

### Fresh (*instantánea*)
: definition

---


## G

---

### Git
: definition

---

### GitHub
: definition

---

### gh-pages
: definition

---

### Goa
: definition

---

### gParted
: definition

---

### GraphQL
: definition

---

### git init
: definition

---

### git add
: definition

---

### git diff
: definition

---

### git status
: definition

---

### git commit

: definition

---

### git log
: definition

---

### git push
: definition

---

### git revert
: definition

---

### git reset
: definition

---

### git restore
: definition

---

### git branch
: definition

---

### git checkout
: definition

---

### git switch
: definition

---


## H

### Hashmap
: definition

---

### Helper
: defintion

---

### Hook <span style="color:cornflowerblue;">(<u>React</u>)</span>
: definition

---

### Htop
: definition

---

### HTML (Hyper Text Markup Language)
: definition

---

### HTTPS (Hypertext Transfer Protocol Secure)
: definition

---

## I

### Immutability
: definition

---

### IntelliJ IDEA
: definition

---

### Inmutability
: definition

---

### Instance Variable
: definition

---


## J

---

### JIT
: definition

---

### JNI
: definition

---

### JPA
: definition

---

### .jsx
: definition

---

### .json (JavaScript Object Notation)
: definition

---

### JSON crack
: definition

---

### Java
: definition

---

### Java EE
: definition

---

### Java Fx
: definition

---

### Java SE
: definition

---

### JavaScript
: definition

---

### Jenkins
: definition

---

### jQuery
: definition

---

### JDA
: definition

---

### JDK (Java Developer Kit)
: definition

---

### JCL
: definition

---

### JUnit <span style="color:darkorange;">(<u>Java</u>)</span>
: defintion

---


## K

## L

### Linux
: definition

---

### Literal Object
: definition

---


## M

---

### Mindset
: definition

---

### Markdown (.md)
: hola que ase

---

### Maven
: definition

---

### MongoDB
: definition

---

### mutability
: definition

---

### MVC (Model View Controller)
: definition

---

## N

---

### Next.js
: definition

---

### Netlify
: definition

---

### Node
: definition

---

### Node.js
: definition

---

### NoSQL
: definition

---

### npm
: definition

---

### npx
: definition

---

### nvm
: definition

---

## O

---

### Obsidian
: definition

---

## P

---

### Polimorfism

---

### Pandoc

---

### Product Backlog
: definition

---

### props <span style="color:cornflowerblue;">(<u>React</u>)</span>
: definition

---

### Polimorfism

---

## Q

---

### Qbernet
: definition

---

### Quarkus
: definition

---

### Quarto
: definition

---


## R

---

### rafce
: defintion

---

### React
: definition

---

### Redux
: definition

---

### (to) render
: definition

---

### Render 
: definition

---

## S

---

### S3
: definition

---

### Sandbox
: definition

---

### Semantic UI <span style="color:cornflowerblue;">(<u>React</u>)</span>
: definition

---

### Script
: definition

---

### SDK (Software Development Kit)
: definition

---

### SpringBoot
: definition

---

### SQL
: definition

---

### SQLite
: definition

---

### sudo
: definition

--- 

### Server
: definition

---

### SCRUM
: definition

---

### Synaptic
: definition

---

### System Design
: definition

---

### Synaptyc Software Manager
: definition

---

### System Monitor
: definition

---

### System Report
: definition

---

### Software sources
: definition

---

### State <span style="color:cornflowerblue;">(<u>React</u>)</span>
: definition

---

### Sublime
: definition

---

### snap
: definition

---


## T

---

### Timeshift
: definition

---

### ThymeLeaf
: definition

---

### TMC Beans
: definition

---

### TOC (*Table of Contents*)
: definition

---

## U

---

### Ubuntu
: definition

---


### UML
: definition

---


## V

---

### Vercel
: definition

---

### Vite <span style="color:cornflowerblue;"><u>(React)</u></span>
: defintion

---

### V8
: definition

---

### VSC (Visual Studio Code)
: definition

---


### VM
: defintion

---


## W

---

### Websocket
: definition

---

### Wizzard
: defintion

---

### webpack
: defintion

---

## X

---

### XML (eXtensible Markup Language)
: defintion

---

## Y

### .yml
: definition

---


## Z